export enum CountryCode {
  US = "US", // United States Of America
  AD = "AD", // Andorra
  AI = "AI", // Anguilla
  AR = "AR", // Argentina
  AU = "AU", // Australia
  AT = "AT", // Austria
  AZ = "AZ", // Azerbaijan
  BS = "BS", // Bahamas
  BH = "BH", // Bahrain
  BB = "BB", // Barbados
  BE = "BE", // Belgium
  BM = "BM", // Bermuda
  BR = "BR", // Brazil
  BG = "BG", // Bulgaria
  CA = "CA", // Canada
  CL = "CL", // Chile
  CN = "CN", // China
  CO = "CO", // Colombia
  CR = "CR", // Costa Rica
  HR = "HR", // Croatia
  CY = "CY", // Cyprus
  CZ = "CZ", // Czech Republic
  DK = "DK", // Denmark
  DO = "DO", // Dominican Republic
  EC = "EC", // Ecuador
  EE = "EE", // Estonia
  FO = "FO", // Faroe Islands
  FI = "FI", // Finland
  FR = "FR", // France
  GE = "GE", // Georgia
  DE = "DE", // Germany
  GH = "GH", // Ghana
  GI = "GI", // Gibraltar
  GB = "GB", // Great Britain
  GR = "GR", // Greece
  HK = "HK", // Hong Kong
  HU = "HU", // Hungary
  IS = "IS", // Iceland
  IN = "IN", // India
  IE = "IE", // Ireland
  IL = "IL", // Israel
  IT = "IT", // Italy
  JM = "JM", // Jamaica
  JP = "JP", // Japan
  KR = "KR", // Korea, Republic of
  LV = "LV", // Latvia
  LB = "LB", // Lebanon
  LT = "LT", // Lithuania
  LU = "LU", // Luxembourg
  MY = "MY", // Malaysia
  MT = "MT", // Malta
  MX = "MX", // Mexico
  MC = "MC", // Monaco
  ME = "ME", // Montenegro
  MA = "MA", // Morocco
  NL = "NL", // Netherlands
  AN = "AN", // Netherlands Antilles
  NZ = "NZ", // New Zealand
  ND = "ND", // Northern Ireland
  NO = "NO", // Norway
  PE = "PE", // Peru
  PL = "PL", // Poland
  PT = "PT", // Portugal
  RO = "RO", // Romania
  RU = "RU", // Russian Federation
  LC = "LC", // Saint Lucia
  SA = "SA", // Saudi Arabia
  RS = "RS", // Serbia
  SG = "SG", // Singapore
  SK = "SK", // Slovakia
  SI = "SI", // Slovenia
  ZA = "ZA", // South Africa
  ES = "ES", // Spain
  SE = "SE", // Sweden
  CH = "CH", // Switzerland
  TW = "TW", // Taiwan
  TH = "TH", // Thailand
  TT = "TT", // Trinidad and Tobago
  TR = "TR", // Turkey
  UA = "UA", // Ukraine
  AE = "AE", // United Arab Emirates
  UY = "UY", // Uruguay
  VE = "VE", // Venezuela
}
